# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['clipbridge/sync_clipboard.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'flask',
        'werkzeug',
        'werkzeug.utils',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'qrcode',
        'clipbridge',
        'clipbridge.config',
        'clipbridge.file_handler',
        'clipbridge.clipboard_manager',
        'clipbridge.response_handler',
        'clipbridge.auth',
        'clipbridge.network_utils',
        'clipbridge.qr_generator',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='clipbridge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
